# week10/k8s/frontend.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2 # Defaulting to 1 replica
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image:  week10acrdevops.azurecr.io/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80 # Nginx runs on port 80 inside the container
        env:
        - name: PRODUCT_API_BASE_URL
          value: http://product-service:8000 # Internal ClusterIP
        - name: ORDER_API_BASE_URL
          value: http://order-service:8001   # Internal ClusterIP
        - name: CUSTOMER_API_BASE_URL
          value: http://customer-service:8002 # Internal ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend # Service name matches
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # The port the service listens on inside the cluster
      targetPort: 80 # The port on the Pod (containerPort where Nginx runs)
      nodePort: 30003 # A high port (30000-32767) on your host machine to access the service (distinct)
  type: LoadBalancer # Exposes the service on a port on each Node's IP