name: Staging Deployment - Temporary Environment

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggers

env:
  STAGING_NAMESPACE: staging-${{ github.run_id }}
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}

jobs:
  deploy-and-test-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Kubernetes context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Create temporary staging namespace
        run: |
          echo "Creating temporary staging namespace: ${{ env.STAGING_NAMESPACE }}"
          kubectl create namespace ${{ env.STAGING_NAMESPACE }}
          echo "✅ Staging namespace created successfully"

      - name: Deploy entire application to staging
        run: |
          echo "Deploying complete application stack to staging..."
          kubectl apply -f k8s/ -n ${{ env.STAGING_NAMESPACE }}
          echo "✅ Application deployed to staging"

      - name: Wait for all pods to be ready
        run: |
          echo "Waiting for all pods in namespace ${{ env.STAGING_NAMESPACE }}..."
          kubectl wait --for=condition=ready pod -l app -n ${{ env.STAGING_NAMESPACE }} --timeout=300s
          echo "✅ All pods are ready!"

      - name: Run automated smoke tests
        run: |
          echo "Running automated smoke tests on staging environment..."

          # Start port-forwards in background
          kubectl port-forward -n ${{ env.STAGING_NAMESPACE }} svc/frontend 8080:80 &
          FRONTEND_PID=$!
          kubectl port-forward -n ${{ env.STAGING_NAMESPACE }} svc/product-service 8000:8000 &
          PRODUCT_PID=$!
          kubectl port-forward -n ${{ env.STAGING_NAMESPACE }} svc/order-service 8001:8001 &
          ORDER_PID=$!
          kubectl port-forward -n ${{ env.STAGING_NAMESPACE }} svc/customer-service 8002:8002 &
          CUSTOMER_PID=$!

          # Give port-forwards time to start
          sleep 10

          echo "Testing frontend..."
          curl -fs http://localhost:8080/ || exit 1

          echo "Testing product-service..."
          curl -fs http://localhost:8000/health || exit 1

          echo "Testing order-service..."
          curl -fs http://localhost:8001/health || exit 1

          echo "Testing customer-service..."
          curl -fs http://localhost:8002/health || exit 1

          echo "Testing product API..."
          curl -fs http://localhost:8000/products/ || exit 1

          echo "Testing order API..."
          curl -fs http://localhost:8001/orders/ || exit 1

          echo "Testing customer API..."
          curl -fs http://localhost:8002/customers/ || exit 1

          echo "✅ All smoke tests passed!"

          # Cleanup port-forwards
          kill $FRONTEND_PID $PRODUCT_PID $ORDER_PID $CUSTOMER_PID

      - name: Collect pod logs on failure
        if: failure()
        run: |
          echo "Collecting logs for debugging..."
          kubectl logs -n ${{ env.STAGING_NAMESPACE }} --all-containers --selector=app > staging-logs.txt || true
        continue-on-error: true

      - name: Upload logs as artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: staging-logs
          path: staging-logs.txt

      - name: Destroy temporary staging environment
        if: always()
        run: |
          echo "Destroying temporary staging namespace: ${{ env.STAGING_NAMESPACE }}"
          kubectl delete namespace ${{ env.STAGING_NAMESPACE }} --ignore-not-found=true
          echo "✅ Staging environment destroyed successfully"

      - name: Logout from Azure
        if: always()
        run: az logout
