name: Staging Deployment - Temporary Environment

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggers

env:
  STAGING_NAMESPACE: staging-${{ github.run_id }}
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}

jobs:
  deploy-and-test-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Kubernetes context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Create temporary staging namespace
        run: |
          echo "Creating temporary staging namespace: ${{ env.STAGING_NAMESPACE }}"
          kubectl create namespace ${{ env.STAGING_NAMESPACE }}
          echo "✅ Staging namespace created successfully"

      - name: Deploy entire application to staging
        run: |
          echo "Deploying complete application stack to staging..."
          kubectl apply -f k8s/ -n ${{ env.STAGING_NAMESPACE }}
          echo "✅ Application deployed to staging"

      - name: Wait for deployments rollout
        run: |
          echo "Waiting for all deployments to finish rollout..."
          kubectl rollout status deployment/frontend -n ${{ env.STAGING_NAMESPACE }} --timeout=300s
          kubectl rollout status deployment/product-service -n ${{ env.STAGING_NAMESPACE }} --timeout=300s
          kubectl rollout status deployment/order-service -n ${{ env.STAGING_NAMESPACE }} --timeout=300s
          kubectl rollout status deployment/customer-service -n ${{ env.STAGING_NAMESPACE }} --timeout=300s
          echo "✅ All deployments rolled out successfully!"

      - name: Run automated smoke tests
        run: |
          echo "Running automated smoke tests on staging environment..."

          # Get ClusterIP of services in the staging namespace
          PRODUCT_IP=$(kubectl get svc product-service -n $STAGING_NAMESPACE -o jsonpath='{.spec.clusterIP}')
          ORDER_IP=$(kubectl get svc order-service -n $STAGING_NAMESPACE -o jsonpath='{.spec.clusterIP}')
          CUSTOMER_IP=$(kubectl get svc customer-service -n $STAGING_NAMESPACE -o jsonpath='{.spec.clusterIP}')
          FRONTEND_IP=$(kubectl get svc frontend -n $STAGING_NAMESPACE -o jsonpath='{.spec.clusterIP}')

          echo "Product service IP: $PRODUCT_IP"
          echo "Order service IP: $ORDER_IP"
          echo "Customer service IP: $CUSTOMER_IP"
          echo "Frontend IP: $FRONTEND_IP"

          echo "Testing product-service..."
          curl -fs http://$PRODUCT_IP:8000/health || { echo "❌ Product-service failed"; exit 1; }

          echo "Testing order-service..."
          curl -fs http://$ORDER_IP:8001/health || { echo "❌ Order-service failed"; exit 1; }

          echo "Testing customer-service..."
          curl -fs http://$CUSTOMER_IP:8002/health || { echo "❌ Customer-service failed"; exit 1; }

          echo "Testing frontend..."
          curl -fs http://$FRONTEND_IP:80/ || { echo "❌ Frontend failed"; exit 1; }

          echo "Testing product API..."
          curl -fs http://$PRODUCT_IP:8000/products/ || { echo "❌ Product API failed"; exit 1; }

          echo "Testing order API..."
          curl -fs http://$ORDER_IP:8001/orders/ || { echo "❌ Order API failed"; exit 1; }

          echo "Testing customer API..."
          curl -fs http://$CUSTOMER_IP:8002/customers/ || { echo "❌ Customer API failed"; exit 1; }

          echo "✅ All smoke tests passed!"



      - name: Collect pod logs on failure
        if: failure()
        run: |
          echo "Collecting logs for debugging..."
          kubectl logs -n ${{ env.STAGING_NAMESPACE }} --all-containers --selector=app > staging-logs.txt || true
        continue-on-error: true

      - name: Upload logs as artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: staging-logs
          path: staging-logs.txt

      - name: Destroy temporary staging environment
        if: always()
        run: |
          echo "Destroying temporary staging namespace: ${{ env.STAGING_NAMESPACE }}"
          kubectl delete namespace ${{ env.STAGING_NAMESPACE }} --ignore-not-found=true
          echo "✅ Staging environment destroyed successfully"

      - name: Logout from Azure
        if: always()
        run: az logout
